window.allExams = window.allExams || {};

window.allExams["exam_noun_noun_100"] = {
    title: "Korean Vocabulary: Noun-to-Noun & Categories (100 Items)",
    description: "Comprehensive exam testing noun relationships, household items, family, clothing, and categories based on official study lists.",
    questions: [
        { q: "What category do 텔레비전, 냉장고, 세탁기, 다리미, 컴퓨터 belong to?", options: ["가전제품", "가구", "의복", "악기"], answer: 0 },
        { q: "What category do 옷장, 책상, 의자, 식탁, 침대, 소파 belong to?", options: ["주택", "가구", "의복", "취미"], answer: 1 },
        { q: "What category do 주택, 아파트, 방, 거실, 부엌 belong to?", options: ["직장", "집", "계절", "교통수단"], answer: 1 },
        { q: "What category do 의복, 한복, 자켓, 티셔츠, 바지, 반바지 belong to?", options: ["학용품/사무용품", "보호구", "의복", "유제품"], answer: 2 },
        { q: "What category do 기타, 피아노, 드럼, 북, 피리 belong to?", options: ["운동", "악기", "취미", "명절"], answer: 1 },
        { q: "What category do 축구, 농구, 야구, 배구, 탁구, 배드민턴 belong to?", options: ["스포츠/운동", "직장", "여행", "교실"], answer: 0 },
        { q: "What category do 동료, 근무, 월급, 회식 belong to?", options: ["가족", "직장", "계절", "우체국"], answer: 1 },
        { q: "What category do 할아버지, 할머니, 아버지, 어머니, 형, 동생, 누나, 아들, 딸 belong to?", options: ["가족", "친구", "은행", "얼굴"], answer: 0 },
        { q: "What category do 봄, 여름, 가을, 겨울 belong to?", options: ["날씨", "계절", "여행", "기념일"], answer: 1 },
        { q: "What category do 기차표, 비행기표, 집, 숙소, 기념품 belong to?", options: ["교통수단", "여행", "취미", "우체국"], answer: 1 },
        { q: "What category do 독서, 등산, 수영, 요리, 축구 belong to?", options: ["취미", "직장", "가전제품", "유제품"], answer: 0 },
        { q: "What category do 공책, 칼, 자, 연필 belong to?", options: ["학용품/사무용품", "보호구", "교실", "교통수단"], answer: 0 },
        { q: "What category do 버스, 택시, 지하철, 기차 belong to?", options: ["교통수단", "보호구", "은행", "얼굴"], answer: 0 },
        { q: "What category do 보안경, 안전화, 귀마개, 목장갑 belong to?", options: ["보호구", "의복", "학용품", "가구"], answer: 0 },
        { q: "What category do 책, 의자, 칠판, 교사 belong to?", options: ["교실", "우체국", "은행", "집"], answer: 0 },
        { q: "What category do 편지, 엽서, 소포 belong to?", options: ["우체국", "교실", "은행", "가전제품"], answer: 0 },
        { q: "What category do 예금, 출금, 송금, 환전 belong to?", options: ["은행", "우체국", "직장", "집"], answer: 0 },
        { q: "What category do 우유, 치즈, 버터, 분유 belong to?", options: ["유제품", "음식", "과일", "채소"], answer: 0 },
        { q: "What category do 눈, 코, 입, 귀 belong to?", options: ["얼굴", "몸", "의복", "가족"], answer: 0 },
        { q: "What category do 설날, 추석, 정월대보름/생일, 스승의 날, 어버이 날 belong to?", options: ["명절/기념일", "계절", "취미", "여행"], answer: 0 },
        // Expanded to 100 items using systematic pairings from Image 1 data
        { q: "Which of the following is listed under 가전제품 (Home Appliances)?", options: ["냉장고", "침대", "티셔츠", "피아노"], answer: 0 },
        { q: "Which of the following is listed under 가전제품 (Home Appliances)?", options: ["세탁기", "소파", "바지", "드럼"], answer: 0 },
        { q: "Which of the following is listed under 가전제품 (Home Appliances)?", options: ["컴퓨터", "책상", "한복", "북"], answer: 0 },
        { q: "Which of the following is listed under 가구 (Furniture)?", options: ["옷장", "냉장고", "축구", "버스"], answer: 0 },
        { q: "Which of the following is listed under 가구 (Furniture)?", options: ["식탁", "세탁기", "야구", "기차"], answer: 0 },
        { q: "Which of the following is listed under 가구 (Furniture)?", options: ["침대", "텔레비전", "농구", "택시"], answer: 0 },
        { q: "Which of the following is listed under 집 (House/Home)?", options: ["아파트", "사무실", "공장", "학교"], answer: 0 },
        { q: "Which of the following is listed under 집 (House/Home)?", options: ["거실", "월급", "우유", "귀마개"], answer: 0 },
        { q: "Which of the following is listed under 의복 (Clothing)?", options: ["자켓", "침대", "냉장고", "축구"], answer: 0 },
        { q: "Which of the following is listed under 의복 (Clothing)?", options: ["반바지", "소파", "세탁기", "농구"], answer: 0 },
        { q: "Which of the following is listed under 악기 (Musical Instruments)?", options: ["피아노", "티셔츠", "책상", "냉장고"], answer: 0 },
        { q: "Which of the following is listed under 악기 (Musical Instruments)?", options: ["피리", "바지", "의자", "세탁기"], answer: 0 },
        { q: "Which of the following is listed under 스포츠/운동 (Sports/Exercise)?", options: ["배구", "컴퓨터", "냉장고", "치즈"], answer: 0 },
        { q: "Which of the following is listed under 스포츠/운동 (Sports/Exercise)?", options: ["배드민턴", "텔레비전", "침대", "우유"], answer: 0 },
        { q: "Which of the following is listed under 직장 (Workplace)?", options: ["근무", "할아버지", "여름", "축구"], answer: 0 },
        { q: "Which of the following is listed under 직장 (Workplace)?", options: ["회식", "어머니", "겨울", "농구"], answer: 0 },
        { q: "Which of the following is listed under 가족 (Family)?", options: ["할머니", "동료", "기차", "냉장고"], answer: 0 },
        { q: "Which of the following is listed under 가족 (Family)?", options: ["누나", "근무", "버스", "세탁기"], answer: 0 },
        { q: "Which of the following is listed under 계절 (Seasons)?", options: ["가을", "축구", "월급", "책상"], answer: 0 },
        { q: "Which of the following is listed under 계절 (Seasons)?", options: ["여름", "야구", "회식", "의자"], answer: 0 },
        { q: "Which of the following is listed under 여행 (Travel)?", options: ["숙소", "냉장고", "근무", "우유"], answer: 0 },
        { q: "Which of the following is listed under 여행 (Travel)?", options: ["기념품", "세탁기", "월급", "치즈"], answer: 0 },
        { q: "Which of the following is listed under 취미 (Hobbies)?", options: ["등산", "아파트", "할아버지", "지하철"], answer: 0 },
        { q: "Which of the following is listed under 취미 (Hobbies)?", options: ["수영", "주택", "어머니", "버스"], answer: 0 },
        { q: "Which of the following is listed under 학용품/사무용품 (School/Office Supplies)?", options: ["연필", "티셔츠", "축구", "냉장고"], answer: 0 },
        { q: "Which of the following is listed under 학용품/사무용품 (School/Office Supplies)?", options: ["공책", "자켓", "야구", "세탁기"], answer: 0 },
        { q: "Which of the following is listed under 교통수단 (Transportation)?", options: ["지하철", "침대", "할머니", "공책"], answer: 0 },
        { q: "Which of the following is listed under 교통수단 (Transportation)?", options: ["택시", "소파", "누나", "연필"], answer: 0 },
        { q: "Which of the following is listed under 보호구 (Protective Gear)?", options: ["안전화", "피아노", "여름", "우유"], answer: 0 },
        { q: "Which of the following is listed under 보호구 (Protective Gear)?", options: ["목장갑", "기타", "겨울", "치즈"], answer: 0 },
        { q: "Which of the following is listed under 교실 (Classroom)?", options: ["칠판", "냉장고", "축구", "기차"], answer: 0 },
        { q: "Which of the following is listed under 교실 (Classroom)?", options: ["교사", "세탁기", "야구", "버스"], answer: 0 },
        { q: "Which of the following is listed under 우체국 (Post Office)?", options: ["엽서", "침대", "농구", "여름"], answer: 0 },
        { q: "Which of the following is listed under 우체국 (Post Office)?", options: ["소포", "소파", "배구", "겨울"], answer: 0 },
        { q: "Which of the following is listed under 은행 (Bank)?", options: ["송금", "할아버지", "냉장고", "책상"], answer: 0 },
        { q: "Which of the following is listed under 은행 (Bank)?", options: ["환전", "어머니", "세탁기", "의자"], answer: 0 },
        { q: "Which of the following is listed under 유제품 (Dairy Products)?", options: ["버터", "축구", "교사", "기차"], answer: 0 },
        { q: "Which of the following is listed under 유제품 (Dairy Products)?", options: ["치즈", "야구", "학생", "버스"], answer: 0 },
        { q: "Which of the following is listed under 얼굴 (Face)?", options: ["코", "냉장고", "가을", "지하철"], answer: 0 },
        { q: "Which of the following is listed under 얼굴 (Face)?", options: ["귀", "세탁기", "여름", "택시"], answer: 0 },
        { q: "Which of the following is listed under 명절/기념일 (Holidays/Anniversaries)?", options: ["추석", "침대", "공책", "안전화"], answer: 0 },
        { q: "Which of the following is listed under 명절/기념일 (Holidays/Anniversaries)?", options: ["생일", "소파", "연필", "목장갑"], answer: 0 },
        { q: "Pair check: Which noun goes with 가전제품?", options: ["텔레비전", "소파", "바지", "피아노"], answer: 0 },
        { q: "Pair check: Which noun goes with 가전제품?", options: ["다리미", "침대", "티셔츠", "드럼"], answer: 0 },
        { q: "Pair check: Which noun goes with 가구?", options: ["책상", "냉장고", "축구", "버스"], answer: 0 },
        { q: "Pair check: Which noun goes with 가구?", options: ["의자", "세탁기", "야구", "기차"], answer: 0 },
        { q: "Pair check: Which noun goes with 집?", options: ["아파트", "월급", "우유", "보안경"], answer: 0 },
        { q: "Pair check: Which noun goes with 집?", options: ["부엌", "근무", "치즈", "귀마개"], answer: 0 },
        { q: "Pair check: Which noun goes with 의복?", options: ["한복", "침대", "냉장고", "피아노"], answer: 0 },
        { q: "Pair check: Which noun goes with 의복?", options: ["자켓", "소파", "세탁기", "기타"], answer: 0 },
        { q: "Pair check: Which noun goes with 악기?", options: ["드럼", "티셔츠", "책상", "냉장고"], answer: 0 },
        { q: "Pair check: Which noun goes with 악기?", options: ["북", "바지", "의자", "세탁기"], answer: 0 },
        { q: "Pair check: Which noun goes with 스포츠/운동?", options: ["농구", "컴퓨터", "냉장고", "치즈"], answer: 0 },
        { q: "Pair check: Which noun goes with 스포츠/운동?", options: ["야구", "텔레비전", "침대", "우유"], answer: 0 },
        { q: "Pair check: Which noun goes with 직장?", options: ["월급", "할아버지", "여름", "축구"], answer: 0 },
        { q: "Pair check: Which noun goes with 직장?", options: ["회식", "어머니", "겨울", "농구"], answer: 0 },
        { q: "Pair check: Which noun goes with 가족?", options: ["할아버지", "동료", "기차", "냉장고"], answer: 0 },
        { q: "Pair check: Which noun goes with 가족?", options: ["동생", "근무", "버스", "세탁기"], answer: 0 },
        { q: "Pair check: Which noun goes with 계절?", options: ["겨울", "축구", "월급", "책상"], answer: 0 },
        { q: "Pair check: Which noun goes with 계절?", options: ["봄", "야구", "회식", "의자"], answer: 0 },
        { q: "Pair check: Which noun goes with 여행?", options: ["기차표", "냉장고", "근무", "우유"], answer: 0 },
        { q: "Pair check: Which noun goes with 여행?", options: ["비행기표", "세탁기", "월급", "치즈"], answer: 0 },
        { q: "Pair check: Which noun goes with 취미?", options: ["독서", "아파트", "할아버지", "지하철"], answer: 0 },
        { q: "Pair check: Which noun goes with 취미?", options: ["등산", "주택", "어머니", "버스"], answer: 0 },
        { q: "Pair check: Which noun goes with 학용품/사무용품?", options: ["칼", "티셔츠", "축구", "냉장고"], answer: 0 },
        { q: "Pair check: Which noun goes with 학용품/사무용품?", options: ["자", "자켓", "야구", "세탁기"], answer: 0 },
        { q: "Pair check: Which noun goes with 교통수단?", options: ["버스", "침대", "할머니", "공책"], answer: 0 },
        { q: "Pair check: Which noun goes with 교통수단?", options: ["택시", "소파", "누나", "연필"], answer: 0 },
        { q: "Pair check: Which noun goes with 보호구?", options: ["보안경", "피아노", "여름", "우유"], answer: 0 },
        { q: "Pair check: Which noun goes with 보호구?", options: ["안전화", "기타", "겨울", "치즈"], answer: 0 },
        { q: "Pair check: Which noun goes with 교실?", options: ["의자", "냉장고", "축구", "기차"], answer: 0 },
        { q: "Pair check: Which noun goes with 교실?", options: ["책", "세탁기", "야구", "버스"], answer: 0 },
        { q: "Pair check: Which noun goes with 우체국?", options: ["편지", "침대", "농구", "여름"], answer: 0 },
        { q: "Pair check: Which noun goes with 우체국?", options: ["엽서", "소파", "배구", "겨울"], answer: 0 },
        { q: "Pair check: Which noun goes with 은행?", options: ["예금", "할아버지", "냉장고", "책상"], answer: 0 },
        { q: "Pair check: Which noun goes with 은행?", options: ["출금", "어머니", "세탁기", "의자"], answer: 0 },
        { q: "Pair check: Which noun goes with 유제품?", options: ["우유", "축구", "교사", "기차"], answer: 0 },
        { q: "Pair check: Which noun goes with 유제품?", options: ["버터", "야구", "학생", "버스"], answer: 0 },
        { q: "Pair check: Which noun goes with 얼굴?", options: ["눈", "냉장고", "가을", "지하철"], answer: 0 },
        { q: "Pair check: Which noun goes with 얼굴?", options: ["입", "세탁기", "여름", "택시"], answer: 0 },
        { q: "Pair check: Which noun goes with 명절/기념일?", options: ["설날", "침대", "공책", "안전화"], answer: 0 },
        { q: "Pair check: Which noun goes with 명절/기념일?", options: ["정월대보름", "소파", "연필", "목장갑"], answer: 0 },
        { q: "Select the group that represents '가구' (Furniture):", options: ["침대, 소파, 의자", "냉장고, 세탁기, 다리미", "티셔츠, 바지, 한복", "버스, 택시, 지하철"], answer: 0 },
        { q: "Select the group that represents '가전제품' (Home Appliances):", options: ["텔레비전, 냉장고, 세탁기", "책상, 의자, 침대", "봄, 여름, 가을", "눈, 코, 입, 귀"], answer: 0 },
        { q: "Select the group that represents '교통수단' (Transportation):", options: ["버스, 택시, 지하철, 기차", "사과, 감자, 고구마", "축구, 야구, 농구", "할아버지, 어머니, 형"], answer: 0 },
        { q: "Select the group that represents '계절' (Seasons):", options: ["봄, 여름, 가을, 겨울", "독서, 등산, 수영", "예금, 출금, 송금", "편지, 엽서, 소포"], answer: 0 },
        { q: "Select the group that represents '얼굴' (Face):", options: ["눈, 코, 입, 귀", "우유, 치즈, 버터", "공책, 칼, 자", "안전화, 귀마개"], answer: 0 },
        { q: "Select the group that represents '가족' (Family):", options: ["어머니, 아버지, 형, 동생", "지하철, 버스, 택시", "회식, 근무, 동료", "가을, 겨울, 봄"], answer: 0 },
        { q: "Select the group that represents '취미' (Hobbies):", options: ["독서, 등산, 수영, 요리", "설날, 추석, 생일", "예금, 환전, 송금", "냉장고, 세탁기, 다리미"], answer: 0 },
        { q: "Select the group that represents '은행' (Bank):", options: ["예금, 출금, 송금, 환전", "의복, 한복, 자켓", "주택, 아파트, 방", "기타, 피아노, 드럼"], answer: 0 },
        { q: "Select the group that represents '우체국' (Post Office):", options: ["편지, 엽서, 소포", "눈, 코, 입, 귀", "봄, 여름, 가을", "우유, 치즈, 버터"], answer: 0 },
        { q: "Select the group that represents '보호구' (Protective Gear):", options: ["보안경, 안전화, 귀마개, 목장갑", "축구, 농구, 야구, 배구", "텔레비전, 라디오, 냉장고", "책, 의자, 칠판, 교사"], answer: 0 },
        { q: "Select the matching pair for '의복' (Clothing):", options: ["한복, 티셔츠, 바지", "식탁, 침대, 소파", "부엌, 거실, 방", "북, 피리, 피아노"], answer: 0 },
        { q: "Select the matching pair for '악기' (Instruments):", options: ["기타, 피아노, 드럼", "축구, 농구, 야구", "봄, 여름, 가을", "버스, 택시, 기차"], answer: 0 },
        { q: "Select the matching pair for '스포츠/운동' (Sports):", options: ["축구, 농구, 배구", "근무, 월급, 회식", "독서, 등산, 수영", "예금, 출금, 송금"], answer: 0 },
        { q: "Select the matching pair for '직장' (Workplace):", options: ["동료, 근무, 월급", "아버지, 어머니, 아들", "집, 숙소, 기념품", "칼, 자, 연필"], answer: 0 },
        { q: "Select the matching pair for '유제품' (Dairy):", options: ["우유, 치즈, 버터", "눈, 코, 입, 귀", "설날, 추석, 생일", "보안경, 안전화"], answer: 0 },
        { q: "What category does '아파트' belong to?", options: ["집", "가구", "의복", "악기"], answer: 0 },
        { q: "What category does '자켓' belong to?", options: ["의복", "가전제품", "보호구", "교통수단"], answer: 0 },
        { q: "What category does '드럼' belong to?", options: ["악기", "스포츠", "취미", "직장"], answer: 0 },
        { q: "What category does '지하철' belong to?", options: ["교통수단", "교실", "우체국", "은행"], answer: 0 },
        { q: "What category does '안전화' belong to?", options: ["보호구", "의복", "가구", "가전제품"], answer: 0 }
    ]
};
